# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 18:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='jobpost',
            name='published_at',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
