# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-28 20:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_auto_20160228_1950'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobpost',
            name='times_viewed',
            field=models.IntegerField(default=0),
        ),
    ]
