# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-04 19:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cities_light', '0006_compensate_for_0003_bytestring_bug'),
        ('jobs', '0004_jobpost_times_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('published_at', models.DateField(blank=True, default=None, null=True)),
                ('slug', models.SlugField(blank=True, default='', max_length=255)),
                ('description', models.TextField()),
                ('requirements', models.TextField()),
                ('about_the_company', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_person', models.CharField(max_length=255)),
                ('web_page', models.URLField(blank=True, default='', max_length=255)),
                ('times_viewed', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='jobs.Category')),
                ('place', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to='cities_light.City')),
            ],
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='category',
        ),
        migrations.RemoveField(
            model_name='jobpost',
            name='place',
        ),
        migrations.DeleteModel(
            name='JobPost',
        ),
    ]
