# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-06 12:37
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_auto_20160304_1902'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='last_viewed_at',
            field=models.DateField(default=datetime.datetime(2016, 3, 6, 12, 37, 39, 121263, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=255, unique=True),
        ),
    ]
