# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-10 19:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0006_auto_20160306_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='last_viewed_at',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
